# Generated by Django 5.1.4 on 2025-01-05 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userorder',
            name='price',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
