# Generated by Django 5.1.4 on 2025-01-06 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(upload_to='items/'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='subcategories',
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.category'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategories',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategories',
            field=models.ManyToManyField(to='products.subcategory'),
        ),
    ]
